### ISSUE TITLE
Suggestion: Change the colour of the Bottom Status Bar when the current script is executing

### ISSUE THREAD

**Issue by ilmax** [tareqimbasher/NetPad#156]
First of all, big kudos and thank you for this gem, keep up the good work!

Sometimes I find it difficult to understand if the current script is executing or it has already completed. There's the little label on the left side of the status bar showing this indication, but I was thinking if adding colours, similar to how Visual Studio does it when you start debugging, would make sense.

I was thinking that we can have 3 colours, the default one when you're editing the script, a colour used when the script is executing and another one (maybe) when the script errored.

If you think this may be valuable, I can also try to contribute such feature myself, but wanted to open this issue before starting to do anything.

**Comment by tareqimbasher** [comment]
Sorry for the late reply. Coloring the status bar when a script is running makes alot of sense in VS because there you're running the a project, and you typically only run one project. Whereas in NetPad you could very likely run a script and then jump to another script while the first one is still running some long process. This means the status bar coloring will have to also switch on/off depending on the script you currently are editing.

While that's fine, and works, it might get confusing I imagine, even more so when side-by-side script editing is introduced (which is planned). I'm not against the idea, kinda like it actually, but I also don't want to remove it once side-by-side comes in. The way I typically check if a script is running is looking at the tab, there is a spinner that appears there when the script is currently running.

That being said, I welcome any and all further thoughts/discussion on this!

And thank you for the kind words, I'm really excited you're finding NetPad useful 🤗
