### ISSUE TITLE
Latest release seems broken

### ISSUE THREAD

**Issue by Jarrich** [tareqimbasher/NetPad#65]
Hi,

I'm new to this project, so please forgive my ignorance.

I've download NetPad for Mac (both versions). The ARM version refused to start ("This app is damaged and cannot be opened").

The x64 version does run but fails on the most basic operation (see screenshot below)

![Screenshot 2023-07-25 at 00 56 12](https://github.com/tareqimbasher/NetPad/assets/11752392/ea745c55-3958-47f4-91ed-cd5609c076f3)

I don't have a lot of other info to share at this moment, just wanted to raise the issue I encountered trying out the project. I have every major .NET SDK installed on this machine.

Regards

**Comment by tareqimbasher** [comment]
The "damaged" message you get on macOS is because NetPad is not a signed application yet. macOS will give you that warning when you try to open an app that isn't signed.

To fix this, you need to either allow unsigned apps or see these release notes  for how to fix:
https://github.com/tareqimbasher/NetPad/releases/tag/v0.3.1

I'll add these instructions to the project's README.

As for the error in your screenshot, a fix for that is already part of the next release (should be out in the next day or so)
 If you just run the script again, the error _should_ go away and show you the output.

Welcome to the project, feel free to ask anything you'd like, there are no wrong questions 🙂

**Comment by Jarrich** [comment]
You're a legend for responding so swiftly. I'll look forward to checking out the next release very soon.
